### ISSUE TITLE
not compatible with evil-surround

### ISSUE THREAD

**Issue by yangguang760** [expez/evil-smartparens#10]
when enable evil-smartparens,
the function of evil-surround:
"Change surrounding

You can change a surrounding with cs<old-textobject><new-textobject>."

not work properly.

For instance,
(te|st)

when cs({

it should be

{te|st}

but when evil-smartparens enabled, it became

{ (t }est)

**Comment by expez** [comment]
@timcharper when `evil-surround-edit` is entered `operation` is always `nil`.  Where does the `operation` value come from?  How can I make sure `evil-smartparens` is passing this along correctly to `evil-surround`?

**Comment by expez** [comment]
Thanks for reporting this, @yangguang760!
