### ISSUE TITLE
Could not get it to work at all

### ISSUE THREAD

**Issue by blak3mill3r** [expez/evil-smartparens#14]
I followed the README, installed the MELPA package w/ Cask, enabled evil-smartparens-mode for emacs-lisp and clojure, and made absolutely sure I had removed all traces of paredit, evil-paredit, and clj-refactor which appears to depend on paredit in some way.

I get nothing, although I've confirmed that the evil-smartparens-mode is active, none of the examples work (they just blow away parens, e.g. dW inside a function call blows away the closing paren)

Any ideas? Or should I just start disabling bits of my config, or start from scratch... ugh

**Comment by blak3mill3r** [comment]
I just tried disabling every minor-mode other than evil-smartparens  (tried this with major mode Emacs-Lisp, and tried with Clojure). I'm confused ... (I am new to emacs, forgive my ignorance)

**Comment by expez** [comment]
Hi 

When `smartparens-mode` is active you can still below away parens.  You have to enable `smartparens-strict-mode` to protect yourself against unbalanced buffers.  Guess I failed to make this clear in the readme.

You don't have to worry about `clj-refactor`, it's using `paredit` internally for some of its refactorings but this is an implementation detail that doesn't affect anything else.

**Comment by blak3mill3r** [comment]
@expez thank you so much for the prompt reply. I will try it later today.

**Comment by blak3mill3r** [comment]
Works like a charm. Thanks again. Here's a change which may help make it obvious to others:

https://github.com/expez/evil-smartparens/pull/15
