### ISSUE TITLE
It hangs when I press shift-d in normal mode

### ISSUE THREAD

**Issue by adouzzy** [expez/evil-smartparens#18]
And it use one of my cpu core up to 100% when I hit shift-d.
Please see if this replicates. It may be a conflict with other plugins.

**Comment by noctuid** [comment]
This happens to me sometimes as well.

**Comment by expez** [comment]
Hey guys, I've seen this a few times myself, but I haven't been able to reproduce it reliably so I can figure out what goes wrong.  Can you guys help me look for situations where this happens?

Both of you probably know this, but `C-g` is emacs for "abort" or "get me out of there", so when the CPU usage goes up to 100% you can hit `C-g` to get emacs to settle down.  

I've noticed that if I hit `D`, encounter this problem,  spam `C-g`, and then hit `D` again it will usually work as intended.  This makes me think that @adouzzy might be right in suggesting a bad interaction with another package, under certain conditions.

**Comment by expez** [comment]
@angelic-sedition is this your entire [.emacs.d](https://github.com/angelic-sedition/dotfiles/tree/master/emacs/.emacs.d)?  I figured I might check which plugins you guys are using to help narrow this down because I'm using around 200 myself.

Are both of you using aggressive-indent-mode?

**Comment by adouzzy** [comment]
Thanks @expez.
After I disabled electric-indent-mode, the problem disappeared.

**Comment by expez** [comment]
@adouzzy do you have a situation where this always happens?  I'd like to fix this bad interaction between the two packages.

**Comment by adouzzy** [comment]
I have used your package for only a few days. I think the conflicts always appended during the period.

**Comment by expez** [comment]
Are you also using `electric-indent-mode`, @angelic-sedition?

**Comment by noctuid** [comment]
That's not my entire .emacs.d (I'm using about 100 packages myself); I am using both aggressive-indent-mode and electric-indent-mode (which I didn't realize I had on). I can't reproduce the problem now by randomly using `D` either. I will try just leaving one on and seeing if I can run into a situation where `D` always does this.
