### ISSUE TITLE
evil-sp-delete-line behavior

### ISSUE THREAD

**Issue by cmccloud** [expez/evil-smartparens#23]
Using spacemacs, with evil, smart-parens, smart-parens-strict, and evil-smartparens enabled in an emacs-lisp buffer

```
(defun test-sexp ()
   |(sexp-A
     (A-first-child))
    (sexp-B)
    (sexp-C
     (C-first-child)
     (C-second-child)))
```

My expectation is that "D" should delete sexp-A and it's child,  but leave sexp-B and sexp-C, instead D results in:

```
(defun test-sexp ()
    |)
```

Is this intended? Others are noticing the same behavior, the discussion is located syl20bnr/spacemacs#2747

**Comment by justbur** [comment]
So the reason I see is here https://github.com/expez/evil-smartparens/blob/master/evil-smartparens.el#L80-L81. D goes up one sexp then backwards and down to find the deletion point.

**Comment by justbur** [comment]
I would think a simple `sp-forward-sexp` would work here, but I'm probably not appreciating all of the possibilities.

**Comment by expez** [comment]
The readme is actually out of sync.   I try to do [readme driven development](http://tom.preston-werner.com/2010/08/23/readme-driven-development.html) and this is what I first wanted, so I get the confusion.  The docstring is correct, though, and says:   "Emulate `sp-kill-sexp' with universal prefix."

In the example in the OP I usually do `da(`, but you could also call `sp-kill-sexp`.  

My goal was to make something that was greater than the sum of its parts (evil and smartparens) and not just duplicate existing behavior across new keybindings.

**Comment by expez** [comment]
There's also [evil-cleverparens](https://github.com/luxbock/evil-cleverparens) to consider, it's quite similar to this package and the author is a great guy.

**Comment by cmccloud** [comment]
thanks!

**Comment by expez** [comment]
To make it clear why I prefer to have it this way, and not like `sp-kill-sexp`:

``` el
(defun test-sexp () |(sexp-A (A-first-child)) (sexp-B) (sexp-C (C-first-child) (C-second-child)))
```

If I now it `D` I get:

``` el
(defun test-sexp () |)
```

which is quite handy!

**Comment by justbur** [comment]
@expez Just a thought. In `evil-sp--get-endpoint-for-sp-kill-sexp`, what if this were the rule?
1. Move to the eol
2. up a sexp
3. backwards and down a sexp

I think that handles both cases.

**Comment by justbur** [comment]
Never mind. That would be weird in this case

``` lisp
  | (a (b 
)
)
```

**Comment by cmccloud** [comment]
@expez I agree, and definitely see the usefulness here.

**Comment by expez** [comment]
You can also delete the sexp in the OP by doing `d<sp-forward-sexp>`.  With the keybindings I've set up for myself this equates to `dM-l`. This variant also supports prefixes so by doing `2dM-l` I can delete the following two sexps.  Isn't it lovely when commands compose in this way? :)
