### ISSUE TITLE
Backspace in Normal Mode

### ISSUE THREAD

**Issue by dbordak** [expez/evil-smartparens#25]
evil-smartparens rebinds backspace in normal mode to `#'sp-backward-delete-char`, which means it actually deletes characters instead of just moving.

Err... This seems to be intentional, but it's not documented and really odd behavior -- it changes the function of the key rather than just preventing it from unbalancing parens... Which it couldn't do anyway.

**Comment by expez** [comment]
Thanks for the report @dbordak. 

I don't think I've ever hit the backspace key in normal mode so I'm blaming this on ignorance :p
