### ISSUE TITLE
How about move out from multiple-nested parens with different types?

### ISSUE THREAD

**Issue by DogLooksGood** [expez/evil-smartparens#27]
Sorry for my poor english, I suppose this should work on this situation.

``` clojure
(hello {:foo "foo"|:bar "bar"})   ;; | = cursor
```

After I press `)` it should become:

``` clojure
(hello {:foo "foo" :bar "bar"})|
```

instead of

``` clojure
(hello {:foo "foo") :bar "bar"}) 
```

I think this is useful in strict-mode, because once i typed mistake `)` it's very inconvenient delete the unmatched `)`.

**Comment by expez** [comment]
This is a bug in smartparens itself.  I opened an issue over there a good while ago https://github.com/Fuco1/smartparens/issues/421

Short of opening a pull-request with a solution to that bug, there's unfortunately nothing I can do.
