### ISSUE TITLE
whitespace after daf and dab

### ISSUE THREAD

**Issue by justbur** [expez/evil-smartparens#29]
Hi, This is a minor annoyance for me, but maybe there's something you can do about it. Here's an example, where I'm using `.` to represent spaces

``` elisp
;;.A.sentence.in.a.comment
(progn.(a).(sequence).(of).(commands))
```

If I `daw` on "sentence", I get

``` elisp
;;.A.in.a.comment
(progn.(a).(sequence).(of).(commands))
```

but `daf` on `sequence` then gives

``` elisp
;;.A.in.a.comment
(progn.(a)..(of).(commands))
```

Notice when I delete "sentence" it also deletes one space, but I'm left with two spaces between `(a)` and `(of)`, which I typically then have to fix right away.

Maybe this is too complicated to fix, but if it's not, I'd appreciate it if the behavior with regards to whitespace leftover was consistent. 

By the way I've been using this package for a while now, and it really makes editing lisp much more pleasant, so thank you.

**Comment by expez** [comment]
What is `f`?  Is that a text-object for a lisp form?  What happens when you do `daf` with just evil enabled?

**Comment by justbur** [comment]
Whoops! I posted this in the wrong repo. Sorry!
