### ISSUE TITLE
"D" key example in README.md incorrect

### ISSUE THREAD

**Issue by accidentalrebel** [expez/evil-smartparens#31]
I just recently installed this package. I was going through the examples when I noticed an incorrect result.

The readme says that this:

```
(let ((foo 1.01))
  (-> foo |(bar baz) qux (quux corge grault) garply))
```

will become this after hitting _D_:

```
(let ((foo 1.01))
  (-> foo |)
```

But the above is missing a closing parenthesis so it should be this:

```
(let ((foo 1.01))
  (-> foo |))
```

Sorry for the nitpick but it did threw me off guard when I was going through it.

I would like to ask permission if I can make a pull request with a fix to it. I have yet to do my very first pull request and I think this is a good and simple start.

Thanks!

**Comment by expez** [comment]
Good eye!  Thanks for spotting this!

A pull-request is most welcome!
