### ISSUE TITLE
Cannot delete lines if quotes are in comments

### ISSUE THREAD

**Issue by jgkamat** [expez/evil-smartparens#49]
If I have the following code (in a c file):
 
```
// |they're here.
```

and I run `evil-sp-change-line`

I would expect the comment to be deleted, but instead, I get the following message:
```
sp-get-string: End of buffer
```

I don't know if this is easy to fix (or possibly out of scope), because I don't know of a way of figuring out if we are in a comment block from the inside. For example:
```
| // they're here.
```
works fine...

**Comment by expez** [comment]
Hi, thanks for the report!

This is unfortunately hard to fix and a bit of an edge-case.  

There's a keybinding for overriding the balance check.  I use it all the time for situations like this.
