### ISSUE TITLE
Emacs hangs completely when using D

### ISSUE THREAD

**Issue by adrianstaniec** [expez/evil-smartparens#51]
I am editing fairly complex .cpp file,
when I use D (evil-sp-delete-line, which should delete until end of line (in a smart way))
emacs hangs and I have to kill it.
I am using 25.3.2 on Linux.
I happens quite consistently (few times per day),
but it hard to come up with minimal example.

**Comment by expez** [comment]
Can you do `M-x toggle-debug-on-quit <RET>`, trigger the problem, interrupt emacs with <kbd>C-g</kbd> and post the subsequent stacktrace?

I suspect this is a variant of https://github.com/expez/evil-smartparens/issues/50

**Comment by mullr** [comment]
I'm getting this with Rust. debug-on-quit says:

```Debugger entered--Lisp error: (quit)
  #f(compiled-function () #<bytecode 0x847f2bfd68c8e21>)()
  syntax-ppss(44709)
  sp--syntax-ppss(44709)
  sp-point-in-comment()
  sp-get-comment-bounds()
  sp--get-string-or-comment-bounds()
  sp-get-paired-expression(nil)
  sp-get-expression(nil)
  sp-get-sexp()
  sp-get-enclosing-sexp(1)
  sp-up-sexp(-1 nil)
  sp-backward-up-sexp()
  evil-sp--depth-at(35716)
  evil-sp--get-endpoint-for-killing()
  evil-sp-delete-line(nil nil nil nil)
  funcall-interactively(evil-sp-delete-line nil nil nil nil)
  command-execute(evil-sp-delete-line)
```
Filed this separately as https://github.com/expez/evil-smartparens/issues/54
