### ISSUE TITLE
Spacemacs Emacs 29.2

### ISSUE THREAD

**Issue by ScratchnSniff0** [expez/evil-smartparens#55]
Not sure if this is a Spacemacs, Emacs, or evil-smartparens.

Error loading autoloads: (file-missing Cannot open load file No such file or directory c:/Users/USERNAME/AppData/Roaming/.emacs.d/elpa/29.2/develop/evil-smartparens-20171210.1513/evil-smartparens-autoloads)

**Comment by expez** [comment]
I'm not sure either, but I can't do anything in this repo to fix your problem.  Try re-installing or check with the spacemacs crew.
